#!/usr/bin/env bash

set -Eeuo pipefail

project_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
deploy_dir="${project_dir}/.deploy"
nginx_config="${deploy_dir}/nginx.conf"
listen_port="8080"
skip_install=false

usage() {
  cat <<'EOF'
Usage: ./deploy.sh [options]

Build RunBeat and generate a local-only Nginx server configuration.

Options:
  --port PORT       Nginx listen port (default: 8080)
  --skip-install    Skip `npm ci` and use the current node_modules
  -h, --help        Show this help

Examples:
  ./deploy.sh
  ./deploy.sh --port 18080
  ./deploy.sh --port 18080 --skip-install
EOF
}

fail() {
  printf '[deploy] Error: %s\n' "$*" >&2
  exit 1
}

while (( $# > 0 )); do
  case "$1" in
    --port)
      (( $# >= 2 )) || fail '--port requires a value'
      listen_port="$2"
      shift 2
      ;;
    --skip-install)
      skip_install=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: $1"
      ;;
  esac
done

[[ "$listen_port" =~ ^[0-9]+$ ]] || fail 'port must be an integer'
listen_port_number=$((10#${listen_port}))
(( listen_port_number >= 1 && listen_port_number <= 65535 )) \
  || fail 'port must be between 1 and 65535'

rubberband_js="${project_dir}/src/assets/wasm/rubberband.js"
rubberband_wasm="${project_dir}/src/assets/wasm/rubberband.wasm"
for runtime_asset in "$rubberband_js" "$rubberband_wasm"; do
  [[ -s "$runtime_asset" ]] || fail \
    "missing prebuilt asset: ${runtime_asset#"${project_dir}/"}; rebuild and commit the Rubber Band WASM files before deploying"
done

command -v npm >/dev/null 2>&1 || fail 'npm is required'

cd "$project_dir"

if [[ "$skip_install" == false ]]; then
  printf '[deploy] Installing locked dependencies...\n'
  npm ci
fi

printf '[deploy] Building production assets...\n'
npm run build

[[ -f "${project_dir}/dist/index.html" ]] \
  || fail 'build completed without dist/index.html'

mkdir -p "$deploy_dir"

cat > "$nginx_config" <<EOF
# Generated by deploy.sh. Run this configuration as the current user.
worker_processes 1;
pid "${deploy_dir}/nginx.pid";
error_log "${deploy_dir}/error.log" warn;

events {
    worker_connections 1024;
}

http {
    access_log off;
    default_type application/octet-stream;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;

    types {
        text/html html;
        text/css css;
        application/javascript js;
        application/json json;
        application/manifest+json webmanifest;
        application/wasm wasm;
        font/woff2 woff2;
        image/png png;
        image/svg+xml svg svgz;
        image/x-icon ico;
    }

    server {
        listen 127.0.0.1:${listen_port_number};
        server_name _;
        server_tokens off;

        root "${project_dir}/dist";
        index index.html;

        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_comp_level 6;
        gzip_types
            application/javascript
            application/json
            application/wasm
            image/svg+xml
            text/css;

        location ^~ /assets/ {
            try_files \$uri =404;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }

        location = /index.html {
            add_header Cache-Control "no-cache";
        }

        location / {
            try_files \$uri \$uri/ /index.html;
            add_header Cache-Control "no-cache";
        }
    }
}
EOF

if command -v nginx >/dev/null 2>&1; then
  printf '[deploy] Validating Nginx configuration...\n'
  nginx -t -p "${deploy_dir}/" -c "$nginx_config"
else
  printf '[deploy] Nginx is not installed; skipped configuration validation.\n'
fi

printf '\n[deploy] Ready.\n'
printf '[deploy] Static files: %s\n' "${project_dir}/dist"
printf '[deploy] Nginx config: %s\n' "$nginx_config"
printf '[deploy] Tunnel origin: http://127.0.0.1:%s\n' "$listen_port_number"
printf '\nStart Nginx:\n'
printf '  nginx -p %q -c %q\n' "${deploy_dir}/" "$nginx_config"
printf '\nReload it after the next deployment:\n'
printf '  nginx -p %q -c %q -s reload\n' "${deploy_dir}/" "$nginx_config"
